//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleInitialInspection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INITIAL INSPECTION PROGRAM")]
        public string PROGRAM_NAME {
            get {
                return ((string)(this["PROGRAM_NAME"]));
            }
            set {
                this["PROGRAM_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ver.1.0.0")]
        public string PROGRAM_VERSION {
            get {
                return ((string)(this["PROGRAM_VERSION"]));
            }
            set {
                this["PROGRAM_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FL-XXXX")]
        public string SOFTWARE_NUMBER {
            get {
                return ((string)(this["SOFTWARE_NUMBER"]));
            }
            set {
                this["SOFTWARE_NUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string SYSTEM_DIO_RELAY_COM_NAME {
            get {
                return ((string)(this["SYSTEM_DIO_RELAY_COM_NAME"]));
            }
            set {
                this["SYSTEM_DIO_RELAY_COM_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIO002")]
        public string MACHINE_RRY {
            get {
                return ((string)(this["MACHINE_RRY"]));
            }
            set {
                this["MACHINE_RRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.02")]
        public double SAFETY_SHUT_DOWN_OFFSET {
            get {
                return ((double)(this["SAFETY_SHUT_DOWN_OFFSET"]));
            }
            set {
                this["SAFETY_SHUT_DOWN_OFFSET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MACHINE_RRY_SD_IN_CHANNEL {
            get {
                return ((int)(this["MACHINE_RRY_SD_IN_CHANNEL"]));
            }
            set {
                this["MACHINE_RRY_SD_IN_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MACHINE_RRY_CLS_ALARM_CHANNEL {
            get {
                return ((int)(this["MACHINE_RRY_CLS_ALARM_CHANNEL"]));
            }
            set {
                this["MACHINE_RRY_CLS_ALARM_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MACHINE_RRY_DIGITAL_CHANNEL {
            get {
                return ((int)(this["MACHINE_RRY_DIGITAL_CHANNEL"]));
            }
            set {
                this["MACHINE_RRY_DIGITAL_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SYSTEM_KIKUSUI_ADDRESS {
            get {
                return ((int)(this["SYSTEM_KIKUSUI_ADDRESS"]));
            }
            set {
                this["SYSTEM_KIKUSUI_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SYSTEM_KIKUSUI_MAX_CURRENT {
            get {
                return ((double)(this["SYSTEM_KIKUSUI_MAX_CURRENT"]));
            }
            set {
                this["SYSTEM_KIKUSUI_MAX_CURRENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double SYSTEM_KIKUSUI_MAX_VOLTAGE {
            get {
                return ((double)(this["SYSTEM_KIKUSUI_MAX_VOLTAGE"]));
            }
            set {
                this["SYSTEM_KIKUSUI_MAX_VOLTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB0::0x0B3E::0x1014::XJ003169::INSTR")]
        public string SYSTEM_KIKUSUI_USB_NAME {
            get {
                return ((string)(this["SYSTEM_KIKUSUI_USB_NAME"]));
            }
            set {
                this["SYSTEM_KIKUSUI_USB_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public long SYSTEM_KIKUSUI_WAITTIME {
            get {
                return ((long)(this["SYSTEM_KIKUSUI_WAITTIME"]));
            }
            set {
                this["SYSTEM_KIKUSUI_WAITTIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("865085")]
        public string SYSTEM_OPHIR_POWER_SERIAL {
            get {
                return ((string)(this["SYSTEM_OPHIR_POWER_SERIAL"]));
            }
            set {
                this["SYSTEM_OPHIR_POWER_SERIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIO000")]
        public string MACHINE_ADI12_8 {
            get {
                return ((string)(this["MACHINE_ADI12_8"]));
            }
            set {
                this["MACHINE_ADI12_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIO000")]
        public string MACHINE_DI_16 {
            get {
                return ((string)(this["MACHINE_DI_16"]));
            }
            set {
                this["MACHINE_DI_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public double SAFETY_OUTPUT_CHECK_TIME {
            get {
                return ((double)(this["SAFETY_OUTPUT_CHECK_TIME"]));
            }
            set {
                this["SAFETY_OUTPUT_CHECK_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SAFETY_OUTPUT_MIN_POWER {
            get {
                return ((int)(this["SAFETY_OUTPUT_MIN_POWER"]));
            }
            set {
                this["SAFETY_OUTPUT_MIN_POWER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SAFETY_PD_OUTPUT_MIN_VOLTAGE {
            get {
                return ((int)(this["SAFETY_PD_OUTPUT_MIN_VOLTAGE"]));
            }
            set {
                this["SAFETY_PD_OUTPUT_MIN_VOLTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int SAFETY_SHUT_DOWN_THRESHOLD_SAFETY {
            get {
                return ((int)(this["SAFETY_SHUT_DOWN_THRESHOLD_SAFETY"]));
            }
            set {
                this["SAFETY_SHUT_DOWN_THRESHOLD_SAFETY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double SPEC_OS_DIFF_MAX {
            get {
                return ((double)(this["SPEC_OS_DIFF_MAX"]));
            }
            set {
                this["SPEC_OS_DIFF_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.5")]
        public double SPEC_OS_DIFF_MIN {
            get {
                return ((double)(this["SPEC_OS_DIFF_MIN"]));
            }
            set {
                this["SPEC_OS_DIFF_MIN"] = value;
            }
        }
    }
}
