namespace FleInitialInspectionManagement.Property
{
    public class FleInitialInspectionSettingDetailProperty
    {
        public string ID { get; set; }
        public string PURCHASE_NO { get; set; }
        public string STEP_NUMBER { get; set; }
        public string TARGET_NAME { get; set; }
        public string TARGET_VALUE { get; set; }
        public string SRS_NEED { get; set; }
        public string SRS_NONE_SPEC { get; set; }
        public string SRS_MIN { get; set; }
        public string SRS_MAX { get; set; }
        public string TEMP_FW_PUMP_NEED { get; set; }
        public string TEMP_FW_PUMP_NONE_SPEC { get; set; }
        public string TEMP_FW_PUMP_MIN { get; set; }
        public string TEMP_FW_PUMP_MAX { get; set; }
        public string TEMP_BW_PUMP_NEED { get; set; }
        public string TEMP_BW_PUMP_NONE_SPEC { get; set; }
        public string TEMP_BW_PUMP_MIN { get; set; }
        public string TEMP_BW_PUMP_MAX { get; set; }
        public string TEMP_FW_TFB_NEED { get; set; }
        public string TEMP_FW_TFB_NONE_SPEC { get; set; }
        public string TEMP_FW_TFB_MIN { get; set; }
        public string TEMP_FW_TFB_MAX { get; set; }
        public string TEMP_BW_TFB_NEED { get; set; }
        public string TEMP_BW_TFB_NONE_SPEC { get; set; }
        public string TEMP_BW_TFB_MIN { get; set; }
        public string TEMP_BW_TFB_MAX { get; set; }
        public string TEMP_FW_SPLICE_NEED { get; set; }
        public string TEMP_FW_SPLICE_NONE_SPEC { get; set; }
        public string TEMP_FW_SPLICE_MIN { get; set; }
        public string TEMP_FW_SPLICE_MAX { get; set; }
        public string TEMP_BW_SPLICE_NEED { get; set; }
        public string TEMP_BW_SPLICE_NONE_SPEC { get; set; }
        public string TEMP_BW_SPLICE_MIN { get; set; }
        public string TEMP_BW_SPLICE_MAX { get; set; }
        public string TEMP_ATTN_NEED { get; set; }
        public string TEMP_ATTN_NONE_SPEC { get; set; }
        public string TEMP_ATTN_MIN { get; set; }
        public string TEMP_ATTN_MAX { get; set; }
        public string TEMP_REF_SPICE_NEED { get; set; }
        public string TEMP_REF_SPICE_NONE_SPEC { get; set; }
        public string TEMP_REF_SPICE_MIN { get; set; }
        public string TEMP_REF_SPICE_MAX { get; set; }
        public string TEMP_OUTPUT_FIBER_NEED { get; set; }
        public string TEMP_OUTPUT_FIBER_NONE_SPEC { get; set; }
        public string TEMP_OUTPUT_FIBER_MIN { get; set; }
        public string TEMP_OUTPUT_FIBER_MAX { get; set; }
        public string TEMP_FLE_REAR_FIBER_NEED { get; set; }
        public string TEMP_FLE_REAR_FIBER_NONE_SPEC { get; set; }
        public string TEMP_FLE_REAR_FIBER_MIN { get; set; }
        public string TEMP_FLE_REAR_FIBER_MAX { get; set; }
        public string TEMP_OUTPUT_SPLICE_POINT_NEED { get; set; }
        public string TEMP_OUTPUT_SPLICE_POINT_NONE_SPEC { get; set; }
        public string TEMP_OUTPUT_SPLICE_POINT_MIN { get; set; }
        public string TEMP_OUTPUT_SPLICE_POINT_MAX { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_NEED { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_NONE_SPEC { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_MIN { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_MAX { get; set; }
        public string ALARM_REF_FUSE_NEED { get; set; }
        public string ALARM_REF_FUSE_NONE_SPEC { get; set; }
        public string ALARM_REF_TEMP_NEED { get; set; }
        public string ALARM_REF_TEMP_NONE_SPEC { get; set; }
        public string ALARM_FET_TEMP_NEED { get; set; }
        public string ALARM_FET_TEMP_NONE_SPEC { get; set; }
        public string ALARM_HS_TEMP_NEED { get; set; }
        public string ALARM_HS_TEMP_NONE_SPEC { get; set; }
        public string ALARM_LDI_MAX_NEED { get; set; }
        public string ALARM_LDI_MAX_NONE_SPEC { get; set; }
        public string ALARM_CAV_TEMP_NEED { get; set; }
        public string ALARM_CAV_TEMP_NONE_SPEC { get; set; }
        public string ALARM_ACC_TEMP_NEED { get; set; }
        public string ALARM_ACC_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_CAV_OUT_NEED { get; set; }
        public string MONITOR_CAV_OUT_NONE_SPEC { get; set; }
        public string MONITOR_CAV_OUT_MIN { get; set; }
        public string MONITOR_CAV_OUT_MAX { get; set; }
        public string MONITOR_REF_FUSE_NEED { get; set; }
        public string MONITOR_REF_FUSE_NONE_SPEC { get; set; }
        public string MONITOR_REF_FUSE_MIN { get; set; }
        public string MONITOR_REF_FUSE_MAX { get; set; }
        public string MONITOR_LDI_NEED { get; set; }
        public string MONITOR_LDI_NONE_SPEC { get; set; }
        public string MONITOR_LDI_MIN { get; set; }
        public string MONITOR_LDI_MAX { get; set; }
        public string MONITOR_REF_TEMP_NEED { get; set; }
        public string MONITOR_REF_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_REF_TEMP_MIN { get; set; }
        public string MONITOR_REF_TEMP_MAX { get; set; }
        public string MONITOR_FET_TEMP_NEED { get; set; }
        public string MONITOR_FET_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_FET_TEMP_MIN { get; set; }
        public string MONITOR_FET_TEMP_MAX { get; set; }
        public string MONITOR_HS_TEMP_NEED { get; set; }
        public string MONITOR_HS_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_HS_TEMP_MIN { get; set; }
        public string MONITOR_HS_TEMP_MAX { get; set; }
        public string MONITOR_CAV1_TEMP_NEED { get; set; }
        public string MONITOR_CAV1_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_CAV1_TEMP_MIN { get; set; }
        public string MONITOR_CAV1_TEMP_MAX { get; set; }
        public string MONITOR_CAV2_TEMP_NEED { get; set; }
        public string MONITOR_CAV2_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_CAV2_TEMP_MIN { get; set; }
        public string MONITOR_CAV2_TEMP_MAX { get; set; }
        public string MONITOR_CAV3_TEMP_NEED { get; set; }
        public string MONITOR_CAV3_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_CAV3_TEMP_MIN { get; set; }
        public string MONITOR_CAV3_TEMP_MAX { get; set; }
        public string MONITOR_ACC_TEMP_NEED { get; set; }
        public string MONITOR_ACC_TEMP_NONE_SPEC { get; set; }
        public string MONITOR_ACC_TEMP_MIN { get; set; }
        public string MONITOR_ACC_TEMP_MAX { get; set; }
        public string INUSE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string NAME_ADDRESS { get; set; }
        public string CREATE_USER { get; set; }
        public string CREATE_DATE { get; set; }
        public string LAST_USER { get; set; }
        public string LAST_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string LD_CURRENT_NEED { get; set; }
        public string LD_CURRENT_NONE_SPEC { get; set; }
        public string LD_CURRENT_MIN { get; set; }
        public string LD_CURRENT_MAX { get; set; }



    }
}