namespace FleInitialInspectionManagement.Property
{
    public class FleInitialInspectionSettingProperty
    {
        public string ID { get; set; }
        public string PURCHASE_NO { get; set; }
        public string OPM_FLOW_MIN { get; set; }
        public string OPM_FLOW_MAX { get; set; }
        public string FL_FLOW_MIN { get; set; }
        public string FL_FLOW_MAX { get; set; }
        public string TS_TEMP_FWPUMP_MIN { get; set; }
        public string TS_TEMP_FWPUMP_MAX { get; set; }
        public string TS_TEMP_BWPUMP_MIN { get; set; }
        public string TS_TEMP_BWPUMP_MAX { get; set; }
        public string TS_TEMP_FWTFB_MIN { get; set; }
        public string TS_TEMP_FWTFB_MAX { get; set; }
        public string TS_TEMP_BWTFB_MIN { get; set; }
        public string TS_TEMP_BWTFB_MAX { get; set; }
        public string TS_TEMP_FWSPLICE_MIN { get; set; }
        public string TS_TEMP_FWSPLICE_MAX { get; set; }
        public string TS_TEMP_BWSPLICE_MIN { get; set; }
        public string TS_TEMP_BWSPLICE_MAX { get; set; }
        public string TS_TEMP_ATTN_MIN { get; set; }
        public string TS_TEMP_ATTN_MAX { get; set; }
        public string TS_TEMP_REFSPICE_MIN { get; set; }
        public string TS_TEMP_REFSPICE_MAX { get; set; }
        public string TS_TEMP_OUTPUTFIBER_MIN { get; set; }
        public string TS_TEMP_OUTPUTFIBER_MAX { get; set; }
        public string TS_TEMP_FLEREARFIBER_MIN { get; set; }
        public string TS_TEMP_FLEREARFIBER_MAX { get; set; }
        public string INUSE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string NAME_ADDRESS { get; set; }
        public string CREATE_DATE { get; set; }
        public string LAST_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string LAST_USER { get; set; }
        public string DESCRIPTION { get; set; }
        public string ALARM_REF_FUSE_NEED { get; set; }
        public string ALARM_REF_TEMP_NEED { get; set; }
        public string ALARM_FET_TEMP_NEED { get; set; }
        public string ALARM_HS_TEMP_NEED { get; set; }
        public string ALARM_LDI_MAX_NEED { get; set; }
        public string ALARM_CAV_TEMP_NEED { get; set; }
        public string ALARM_ACC_TEMP_NEED { get; set; }
        public string TEMP_CRITERIA_OUTPUT_SPLICE_POINT_MIN { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_MIN { get; set; }
        public string TEMP_CRITERIA_OUTPUT_SPLICE_POINT_MAX { get; set; }
        public string TEMP_OUTPUT_SPLICE_QBH_POINT_MAX { get; set; }
        public string MONITOR_CAV_OUT_SPEC_NEED { get; set; }
        public string MONITOR_CAV_OUT_MIN { get; set; }
        public string MONITOR_CAV_OUT_MAX { get; set; }
        public string MONITOR_REF_FUSE_SPEC_NEED { get; set; }
        public string MONITOR_REF_FUSE_MIN { get; set; }
        public string MONITOR_REF_FUSE_MAX { get; set; }
        public string MONITOR_LDI_SPEC_NEED { get; set; }
        public string MONITOR_LDI_MIN { get; set; }
        public string MONITOR_LDI_MAX { get; set; }
        public string MONITOR_REF_TEMP_SPEC_NEED { get; set; }
        public string MONITOR_REF_TEMP_MIN { get; set; }
        public string MONITOR_REF_TEMP_MAX { get; set; }
        public string MONITOR_FET_TEMP_SPEC_NEED { get; set; }
        public string MONITOR_FET_TEMP_MIN { get; set; }
        public string MONITOR_FET_TEMP_MAX { get; set; }
        public string MONITOR_HS_TEMP_SPEC_NEED { get; set; }
        public string MONITOR_HS_TEMP_MIN { get; set; }
        public string MONITOR_HS_TEMP_MAX { get; set; }
        public string MONITOR_CAV_TEMP1_SPEC_NEED { get; set; }
        public string MONITOR_CAV_TEMP1_MIN { get; set; }
        public string MONITOR_CAV_TEMP1_MAX { get; set; }
        public string MONITOR_CAV_TEMP2_SPEC_NEED { get; set; }
        public string MONITOR_CAV_TEMP2_MIN { get; set; }
        public string MONITOR_CAV_TEMP2_MAX { get; set; }
        public string MONITOR_CAV_TEMP3_SPEC_NEED { get; set; }
        public string MONITOR_CAV_TEMP3_MIN { get; set; }
        public string MONITOR_CAV_TEMP3_MAX { get; set; }
        public string MONITOR_ACC_TEMP_SPEC_NEED { get; set; }
        public string MONITOR_ACC_TEMP_MIN { get; set; }
        public string MONITOR_ACC_TEMP_MAX { get; set; }

    }
}